---
- name: 'creating AD objects'
  hosts: windows
  vars_files:
    - users_list.yml
  gather_facts: true
  tasks:
    - name: 'creating domain controller users'
      microsoft.ad.user:
        name: '{{ item }}'
        password: 'B0bP4ssw0rd'
        state: present
      loop: '{{ users }}'
