---
- name: 'creating AD objects'
  hosts: windows
  gather_facts: true
  tasks:
    - name: 'creating domain controller users'
      microsoft.ad.user:
        name: 'bob'
        firtname: 'Bob'
        surname: 'Smith'
        company: 'BobCo'
        password: 'B0bP4ssw0rd'
        state: present
        groups:
          set:
          - Domain Admins
