---
- name: listen urls events
  hosts: all 
  
  sources: 
   - name: Match web server events
     ansible.eda.url_check:
       urls:
        - http://10.0.32.207/index.html
       delay: 5


  rules: 
   - name: Exec play
     condition: event.url_check == "up"
     action:
       run_playbook: 
         name: Deploy_Container_APP1

