---
- name: listen urls events
  hosts: all 
  
  sources: 
   - name: Match web server events
     ansible.eda.url_check:
       urls:
        - http://10.0.32.77/
       delay: 5


  rules: 
   - name: Exec play
     condition: event.url_check.status == "down"
     actions:
       run_job_template: 
         name: Deploy_Container_APP1
         organization: DEMO

